name: inject.example.coffee
description: A simple example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^0.7.11
  build_test: ^0.10.0
  inject_generator:
    path: ../../package/inject_generator
  test: ^0.12.32+1
